### ISSUE TITLE
Incompatible plugins do not render properly.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11719]
**Describe the bug**
Several users have reported that they are seeing a message for two plugins being incompatible where the right side is blank. This could to be related to this part of the code: https://github.com/Nexus-Mods/extension-plugin-management/blob/877fae271416b26a12e2abbd5dcc2fc564d9bb08/src/views/UserlistEditor.tsx#L212

The "references" can be either a string or an [ILootReference](https://github.com/Nexus-Mods/extension-plugin-management/blob/877fae271416b26a12e2abbd5dcc2fc564d9bb08/src/types/ILOOTList.ts#L33). I believe it's the latter type that is causing the rendering to fail?

**To Reproduce**
1. Install these two mods: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=247132&nmm=1&game_id=1704, https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=195523&nmm=1&game_id=1704
2. Enable all plugins.
3. See LOOT error with missing data on the right side. 

**Expected behavior**
The message is properly rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/31670524/163789794-b8a341e2-b497-411d-9e1b-b2d8a439c889.png)

Masterlist reference:
```yaml
  - name: MLU.esp
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/3058/'
        name: MorrowLoot Ultimate
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/2295/'
        name: Morrowloot Ultimate Simplified
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/10/'
        name: Another Sorting Mod - MLU.esp Replacer
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/17653/'
        name: (SJG) OMEGA - The Modular Gameplay Overhaul
    group: Economy
    inc:
      - WACCF_BashedPatchLvlListFix.esp
    msg:
      - type: say
        content: 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A third party patch is available here: %2%'
        subs:
          - '[Legacy of the Dragonborn](https://www.nexusmods.com/skyrimspecialedition/mods/11802/)'
          - '[Legacy of the Dragonborn Patches (Official)](https://www.nexusmods.com/skyrimspecialedition/mods/30980/)'
        condition: 'active("LegacyoftheDragonborn.esm") and not active("DBM_MorrowlootUltimate_Patch.esp") and (version("LegacyoftheDragonborn.esm", "5.0.24", >=) or (not checksum("LegacyoftheDragonborn.esm", 31563183) and not checksum("LegacyoftheDragonborn.esm", 6736FB94) and not checksum("LegacyoftheDragonborn.esm", CB82480D)))'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Advanced Adversary Encounters - Ultimate
        condition: 'active("AAE Ultimate Edition.esp") and not active("MLU - AAE Ultimate Edition.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - AI Overhaul
        condition: 'active("AI Overhaul.esp") and not active("MLU - AI Overhaul.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Ars Metallica - Smithing Enhancements
        condition: 'active("Ars Metallica.esp") and not active("MLU - Ars Metallica Patch.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Complete Crafting Overhaul Remastered
        condition: 'active("Complete Crafting Overhaul_Remastered.esp") and not active("MLU - CCOR.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Cosmetic Vampire Overhaul
        condition: 'active("CosmeticVampireOverhaul.esp") and not active("MLU - CosmeticVampireOverhaul.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Cutting Room Floor
        condition: 'active("Cutting Room Floor.esp") and not active("MLU - CRF.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Immersive Armors
        condition: 'active("Hothtrooper44_ArmorCompilation.esp") and not active("MLU - Immersive Armors.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Improved Closefaced Helmets
        condition: 'active("imp_helm_legend.esp") and not active("OMEGA MLU Improved Closefaced Helmets.esp") and not active("MLU - Improved Closefaced Helmets.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Improved Daedric Artifacts
        condition: 'active("ImprovedDaedricArtifacts.esp") and not active("MLU - ImprovedDaedricArtifacts.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - INIGO
        condition: 'active("Inigo.esp") and not active("MLU - Inigo.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - InsanitySorrow Weapons Pack
        condition: 'active("InsanitySorrow Weapons Pack.esp") and not active("MLU - InsanitySorrow Weapons Pack.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - "JK's The Drunken Huntsman"
        condition: "active(\"JKs The Drunken Huntsman.esp\") and not active(\"MLU - JK's The Drunken Hunstman.esp\") and not active(\"MLU Patches Merged.esp\")"
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Lore Weapon Expansion
        condition: 'active("Lore Weapon Expansion.esp") and not active("LegacyoftheDragonborn.esm") and not active("MLU - Lore Weapon Expansion.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Lore Weapon Expansion and Legacy of the Dragonborn
        condition: 'active("Lore Weapon Expansion.esp") and active("LegacyoftheDragonborn.esm") and not active("MLU - Lore Weapon Expansion - LOTD Version.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Mainland Stalhrim
        condition: 'active("MainlandStalhrim.esp") and not active("MLU - Mainland Stalhrim.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Simple Magic Rebalance
        condition: 'active("Simple Magic Rebalance.esp") and (checksum("Simple Magic Rebalance.esp", D55C09E9) or checksum("Simple Magic Rebalance.esp", 971ADB2B)) and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Skyrim Revamped - Complete Enemy Overhaul
        condition: 'active("Skyrim Revamped - Complete Enemy Overhaul.esp") and not active("MLU - Skyrim Revamped Complete Enemy Overhaul.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Summermyst - Enchantments of Skyrim
        condition: 'active("Summermyst - Enchantments of Skyrim.esp") and not active("MLU - Summermyst.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Unique Uniques
        condition: 'active("Unique Uniques.esp") and checksum("Unique Uniques.esp", 31DB2011) and not active("MLU - Unique Uniques.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Weapons Armor Clothing and Clutter Fixes
        condition: 'active("Weapons Armor Clothing & Clutter Fixes.esp") and not active("MLU - WaCCF.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - Windsong Immersive Character Overhaul
        condition: 'active("WICO - Immersive People.esp") and not active("MLU - WICO.esp") and not active("MLU Patches Merged.esp")'
      - type: say
        content: "You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
        subs:
          - "Zim's Immersive Artifacts"
        condition: 'active("ZIA_Complete Pack_V4.esp") and not active("MLU - ZIA.esp") and not active("MLU Patches Merged.esp") and not active("ScopedBows.esp")'
      - type: say
        content: 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A third party patch is available here: %2%'
        subs:
          - '[Scoped Bows](https://www.nexusmods.com/skyrimspecialedition/mods/912/)'
          - '[Scoped Bows Compatibility Kit - SBCK](https://www.nexusmods.com/skyrimspecialedition/mods/19495/)'
        condition: 'active("ScopedBows.esp") and not active("ScopedBows_MLU Patch.esp") and not active("ScopedBows_MLU_ZIA Patch.esp")'
    tag:
      - Actors.ACBS
      - Actors.AIData
      - Actors.CombatStyle
      - Actors.Spells
      - Actors.Stats
      - EnchantmentStats
      - Graphics
      - Invent.Add
      - Invent.Change
      - Invent.Remove
      - Keywords
      - NPC.Class
      - ObjectBounds
      - Outfits.Add
      - Outfits.Remove
      - Text
    dirty:
      - util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        detail: 'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'
        crc: 2424411165
        itm: 8
      - util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        detail: 'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'
        crc: 1282539792
        itm: 5
      - util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        detail: 'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'
        crc: 2875184949
        itm: 271
      - util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        detail: 'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'
        crc: 2117391761
        itm: 2
      - util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        detail: 'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'
        crc: 2731566917
        itm: 2
```

```yaml
  - name: WACCF_BashedPatchLvlListFix.esp
    url:
      - 'https://www.nexusmods.com/skyrimspecialedition/mods/18994/'
    group: Leveled List Modifiers
    msg:
      - type: say
        content: This plugin is optional.
      - type: warn
        content: 'Requires: %1%'
        subs:
          - '[Wrye Bash](https://www.nexusmods.com/skyrimspecialedition/mods/6837) or [Smash](https://github.com/matortheeternal/smash/releases)'
        condition: "not file(\"Bashed Patch.*\\.esp\") and not file(\"Smashed Patch.esp\")"
    clean:
      - crc: 3559418066
        util: SSEEdit v4.0.3h (Hotfix 1)
```

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**
